# Generated by Django 5.1.2 on 2025-03-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DSAQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Hard', 'Hard'), ('Medium', 'Medium'), ('Easy', 'Easy')], max_length=10)),
                ('problem_statement', models.TextField()),
                ('test_cases', models.JSONField()),
                ('solution', models.TextField()),
                ('subdomain', models.JSONField()),
            ],
        ),
    ]
